[env]
TERM = "xterm-256color"


[font]
size = 19.0
[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"
[font.italic]
family = "Iosevka Nerd Font"
style = "Regular"
[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

# [font]
# size = 16.0
# [font.bold]
# family = "FiraCode Nerd Font"
# style = "Bold"
# [font.italic]
# family = "FiraCode Nerd Font"
# style = "Regular"
# [font.normal]
# family = "FiraCode Nerd Font"
# style = "Regular"

# [font.bold]
# family = "Cascadia Code"
# style = "Bold"
# [font.italic]
# family = "Cascadia Code"
# style = "Italic"
# [font.normal]
# family = "Cascadia Code"
# style = "Regular"

# [font.bold]
# family = "JetBrainsMono Nerd Font"
# style = "Bold"
# [font.italic]
# family = "JetBrainsMono Nerd Font"
# style = "Italic"
# [font.normal]
# family = "JetBrainsMono Nerd Font"
# style = "Regular"

# [font.bold]
# family = "Terminess Nerd Font"
# style = "Bold"
# [font.italic]
# family = "Terminess Nerd Font"
# style = "Italic"
# [font.normal]
# family = "Terminess Nerd Font"
# style = "Regular"

# Rose-pine

# [colors.primary]
# foreground = "#e0def4"
# background = "#191724"
# dim_foreground = "#908caa"
# bright_foreground = "#e0def4"
#
# [colors.cursor]
# text = "#e0def4"
# cursor = "#524f67"
#
# [colors.vi_mode_cursor]
# text = "#e0def4"
# cursor = "#524f67"
#
# [colors.search.matches]
# foreground = "#908caa"
# background = "#26233a"
#
# [colors.search.focused_match]
# foreground = "#191724"
# background = "#ebbcba"
#
# [colors.hints.start]
# foreground = "#908caa"
# background = "#1f1d2e"
#
# [colors.hints.end]
# foreground = "#6e6a86"
# background = "#1f1d2e"
#
# [colors.line_indicator]
# foreground = "None"
# background = "None"
#
# [colors.footer_bar]
# foreground = "#e0def4"
# background = "#1f1d2e"
#
# [colors.selection]
# text = "#e0def4"
# background = "#403d52"
#
# [colors.normal]
# black = "#26233a"
# red = "#eb6f92"
# green = "#31748f"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ebbcba"
# white = "#e0def4"
#
# [colors.bright]
# black = "#6e6a86"
# red = "#eb6f92"
# green = "#31748f"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ebbcba"
# white = "#e0def4"
#
# [colors.dim]
# black = "#6e6a86"
# red = "#eb6f92"
# green = "#31748f"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ebbcba"
# white = "#e0def4"

# Colors (Gruvbox Material Dark Medium)

# [colors.primary]
# background = '#282828'
# foreground = '#dfbf8e'
#
# [colors.normal]
# black   = '#665c54'
# red     = '#ea6962'
# green   = '#a9b665'
# yellow  = '#e78a4e'
# blue    = '#7daea3'
# magenta = '#d3869b'
# cyan    = '#89b482'
# white   = '#dfbf8e'
#
# [colors.bright]
# black   = '#928374'
# red     = '#ea6962'
# green   = '#a9b665'
# yellow  = '#e3a84e'
# blue    = '#7daea3'
# magenta = '#d3869b'
# cyan    = '#89b482'
# white   = '#dfbf8e'
