[font]
size = 12.0
# use_thin_strokes = true

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0
